### ISSUE TITLE
Supported Versions - 1.19.2?

### ISSUE THREAD

**Issue by klikli-dev** [Tslat/SmartBrainLib#17]
Will 1.19.2 receive feature updates or only 1.19.3?

In my mods I currently support 1.18.2, 1.19.2, and 1.19.3.
I am considering to slowly migrate my AI towards SBL and would like to plan ahead which versions to cherry-pick the related commits over. It seems in the 1.19.3 upgrade commit a variety of utilities was added that is missing from 1.19.2.

Can you shed some light?

Much appreciated!

**Comment by Tslat** [comment]
Unfortunately I only really have the time to maintain SBL for a single version, so it'll always be for the latest current MC version
The lib itself is still fully functional on previous versions, so it's not a total loss

You're welcome to PR the backports if you want, but it'd have to be PR'd across all 3 branches to maintain parity (1.19.2 SBL and lower was not multiloader)

**Comment by klikli-dev** [comment]
Thanks for the clarification - that makes sense!
I'll play around with SBL a bit and then decide how to proceed.

So far things look straightforward, if any questions arise I'll join discord :) 

Great work on this!
