### ISSUE TITLE
java.lang.NoClassDefFoundError: net/tslat/smartbrainlib/api/util/BrainUtils

### ISSUE THREAD

**Issue by 1201for** [Tslat/SmartBrainLib#31]
[crash-2023-04-03_17.35.19-server.txt](https://github.com/Tslat/SmartBrainLib/files/11142716/crash-2023-04-03_17.35.19-server.txt)

**Comment by Tslat** [comment]
Yeah aoa uses an older version of SBL
Honestly aoa in 1.19.2 isn't meant for survival anyway. you might as well remove it
