### ISSUE TITLE
Artifacts published on maven are not in intermediary mappings

### ISSUE THREAD

**Issue by Jamalam360** [Tslat/SmartBrainLib#33]
I believe this is what's going on. I asked in the Quilt Discord and apparently you've had this before so it's probably a simple fix?

![image](https://user-images.githubusercontent.com/56727311/231549982-dd11ff43-529a-4da6-9281-bba181a0c0f9.png)

Thank you :)

**Comment by Tslat** [comment]
Which version are you trying to use?

**Comment by Tslat** [comment]
And what issue are you having.. exactly?

That setup is working fine for me in dev currently and for plenty of others

**Comment by Jamalam360** [comment]
The wiki suggests depending on both the Fabric and Common jars.

Decompiling these artifacts from the maven, the Fabric jar is in intermediary mappings as expected, but the common jar is not, it is in mojmap. 

This means that people that don't use mojmap (i.e. yarn/quilt mappings user) cannot depend on the common jar.

## Decompilation of random class to show issue

Fabric jar decompilation:
![image](https://user-images.githubusercontent.com/56727311/232291678-1c876c88-94d6-4008-90e6-c0647704ca2a.png)

Common jar decompilation (mojmap names):
![image](https://user-images.githubusercontent.com/56727311/232291712-3f4b6687-2625-42c9-87a2-6db873a965dd.png)

**Comment by Jamalam360** [comment]
From a simple `diff` command on the extracted jars, it seems the Fabric and Common jars are the same directory and file wise, apart from the mappings. Maybe Fabric users only need to depend on the Fabric jar, not the common one as well? Documentation outdated?
