### ISSUE TITLE
Fabric Version Crashes with Sinytra Connector

### ISSUE THREAD

**Issue by AzureDoom** [Tslat/SmartBrainLib#44]
I have been testing my Fabric mods with [Sinytra Connector](https://modrinth.com/mod/connector) and noticed it crashes with the Fabric version. The workaround has been to use the Forge version with no issues in my SBL-powered mods. 

Issue reported to Sinytra here: https://github.com/Sinytra/Connector/issues/232

I just thought I'd share it here in case other users report issues.

**Comment by Tslat** [comment]
No Crash report?

**Comment by AzureDoom** [comment]
No crash report was generated, just closed the game and sent me back to the launcher. Here is the log I posted in the Connector issue. https://gist.github.com/AzureDoom/563b485ce46b223119d46215daf29aa9

**Comment by Tslat** [comment]
Yeah nothing in that =/

**Comment by AzureDoom** [comment]
Yeah, it's quite a weird bug. I found it when I was testing my mods for Connector. The Forge version works perfectly with the Fabric mods, so there is at least that workaround.

**Comment by Su5eD** [comment]
The issue was fixed on my side, so this can be closed now.
