### ISSUE TITLE
downgrade required for occultism

### ISSUE THREAD

**Issue by yaitsbilly** [Tslat/SmartBrainLib#48]
getting this error.

16:45:06] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'smartbrainlib', Requested by: 'occultism', Expected range: '[1.11,)', Actual version: '[MISSING]'

Downgrading works.

**Comment by Tslat** [comment]
That sounds like it has nothing to do with sbl and everything to do with occultism? lol
