### ISSUE TITLE
Server Crash - java.lang.NoClassDefFoundError: net/minecraftforge/common/util/BrainBuilder

### ISSUE THREAD

**Issue by DonorKrovi** [Tslat/SmartBrainLib#49]
https://github.com/klikli-dev/occultism/issues/992
SmartBrainLib-forge-1.20.1-1.12

**Comment by RushanM** [comment]
The exact same crash just happened on my server, but not because of Occultism. Here's the log.
[crash-2024-03-20_17.29.15-server.txt](https://github.com/Tslat/SmartBrainLib/files/14681030/crash-2024-03-20_17.29.15-server.txt)

**Comment by Tslat** [comment]
Yeah forge broke stuff
Use SBL for NeoForge
