### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by FlooferLand** [Tslat/SmartBrainLib#50]
The Wiki page seems to be heavily outdated.
Trying to follow it leads to errors about the overridable `brainProvider` method missing, and all of the example projects are outdated as well _(last changes were done a year ago)_
It's already a daunting enough task as a beginner trying to base my mod on a sorta obscure library. Not having any up to date documentation for it as well is terrifying.

**Comment by Tslat** [comment]
No, it's not

If you have a problem, join the discord and ask about it
The documentation is fine though
