### ISSUE TITLE
Memories do not get loaded when saveMemories is true

### ISSUE THREAD

**Issue by MerchantPug** [Tslat/SmartBrainLib#56]
There's no deserialization.

**Comment by Tslat** [comment]
What are you using saved memories for, out of curiosity?

It's a point of performance cost and I'm not even sure I can work out what the use case is for this lol

**Comment by MerchantPug** [comment]
> What are you using saved memories for, out of curiosity?
> 
> It's a point of performance cost and I'm not even sure I can work out what the use case is for this lol

Ah, okay, I didnt know it was a point of performance cost.

But I guess I'm storing stuff like homes, but i guess that can be done with just synced entity data.

**Comment by Tslat** [comment]
Don't even need a field, just save/load it in addAdditional and readAdditional like you would any other serializeable entity data

For a long time I've been contemplating just removing the option to serialize memories entirely, but I'm not sure yet
I'll look into this issue regardless

**Comment by MerchantPug** [comment]
That's exactly what I did. Thanks for the responses.
