### ISSUE TITLE
Crash of Occultism mod because of SmartBrainLib

### ISSUE THREAD

**Issue by uhloin** [Tslat/SmartBrainLib#57]
Details and crash log are here:
https://github.com/klikli-dev/occultism/issues/1029

**Comment by klikli-dev** [comment]
@uhloin I just noticed that you are using neoforge - but 1.13 is forge only (see tags on curseforge), which would explain the crash.  
1.12 has a neoforge version it seems

**Comment by Tslat** [comment]
Hm?

Neoforge has a 1.13 version as well

https://www.curseforge.com/minecraft/mc-mods/smartbrainlib/files/4981374

**Comment by Tslat** [comment]
1.13 Works fine

You're using Forge 1.13 on a Neoforge loader.

If you want to use NeoForge, use the NeoForge version. Forge broke brains in 1.20.1 and so they're no longer compatible between forge and neoforge

**Comment by uhloin** [comment]
Thank you too. There note on the NeoForge site about compatibility for 1.20.1, so I always used Forge filter because of some mods haven't separate versions for NeoForge 1.20.1. Yours is first among I use. 1.13 for neoforge version works fine.
