### ISSUE TITLE
Maven repository for SBL no longer exists

### ISSUE THREAD

**Issue by bluebear94** [Tslat/SmartBrainLib#62]
The Maven repository given in the [“Getting Started”](https://github.com/Tslat/SmartBrainLib/wiki/Getting-Started) page of the wiki (`https://dl.cloudsmith.io/public/tslat/sbl/maven/`) no longer exists. Has it moved elsewhere?

**Comment by Tslat** [comment]
It exists just fine

You just can't browse to that URL directly because it's not a browseable maven at that location.

**Comment by bluebear94** [comment]
Alright, found out that it happened because `SmartBrainLib-fabric-1.20.6:1.14.2` is missing from the maven (I have to use `SmartBrainLib-fabric-1.20.5:1.14.2` instead).

**Comment by Tslat** [comment]
🤔 

I'll get new versions up on all the platforms soon, that's definitely an issue there
