### ISSUE TITLE
[1.21] Mod Crashing when starting game

### ISSUE THREAD

**Issue by Periam** [Tslat/SmartBrainLib#63]
After installing the mod for the latest MC 1.21, the game crash

Minecraft Version1.21
Forge 51.0.8
SmartBrainLib-forge-1.21-1.14.2

No crash log report.

**Comment by Tslat** [comment]
It crashes with no crash report?
That seems extremely unlikely lol

**Comment by Tslat** [comment]
Try 1.14.3
