### ISSUE TITLE
SBL Skeleton missing SetWalkTargetToAttackTarget behaviour

### ISSUE THREAD

**Issue by FlashFyreMods** [Tslat/SmartBrainLib#65]
Vanilla skeletons target and run towards the player if they don't have a bow, whereas the SBL skeleton just stands still if it doesn't have a bow equipped. 

You can test this using /summon smartbrainlib:sbl_skeleton ~ ~ ~ {Equipment:[]}

I was using this mob as a reference and was wondering for far too long why my mob wasn't walking towards the player. Definitely not a big issue but I hate questioning whether examples are correct lol.

**Comment by Tslat** [comment]
Lol I guess I could include that
I wasn't designing it to be _that_ in-depth though ;)

**Comment by FlashFyreMods** [comment]
Hahaha sure but CLEARLY it is not a faithful recreation without it x)
