### ISSUE TITLE
Can't find Fabric 1.21.1 Dependency from the Maven Repo

### ISSUE THREAD

**Issue by JR1811** [Tslat/SmartBrainLib#69]
Is the [Getting Started](https://github.com/Tslat/SmartBrainLib/wiki/Getting-Started) page still up to date or do I have the wrong version specified? Im working in 1.21.1 Fabric

```
repositories {
	maven {
		name = "SmartBrainLib (SBL) Maven Repo"
		url = "https://dl.cloudsmith.io/public/tslat/sbl/maven/"
	}
}
```

```
dependencies {
        // ...
	modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${project.minecraft_version}:${project.sbl_version}"
}
```

```
# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.15.11

...

# Dependencies
fabric_version=0.102.1+1.21.1
sbl_version=1.14.5
```

`Could not find net.tslat.smartbrainlib:SmartBrainLib-fabric-1.21.1:1.14.5`

`https://dl.cloudsmith.io/public/tslat/sbl/maven/net/tslat/smartbrainlib/SmartBrainLib-fabric-1.21.1/1.14.5/SmartBrainLib-fabric-1.21.1-1.14.5.pom`

**Comment by Tslat** [comment]
it'll be 1.21

1.21.1 didn't need a repackage

If I do another new version it'll be packaged as 1.21.1
