### ISSUE TITLE
NeoForge file tagged with fabric

### ISSUE THREAD

**Issue by NFLD99** [Tslat/SmartBrainLib#71]
SmartBrainLib NeoForge 1.21.1-1.15 is tagged as fabric compatible, its not
https://www.curseforge.com/minecraft/mc-mods/smartbrainlib/files/5654991

**Comment by Tslat** [comment]
wtf

**Comment by Tslat** [comment]
Wait, it's not marked as fabric on my side?

![image](https://github.com/user-attachments/assets/04d4013b-3c45-47d8-8f43-8159a42e9230)
![image](https://github.com/user-attachments/assets/c1aaf48c-97d4-482c-b01e-c21d029f90dd)
