### ISSUE TITLE
[1.21.3] Crash because of mixins related to SBL

### ISSUE THREAD

**Issue by Tron-Creeper2** [Tslat/SmartBrainLib#75]
Mod Version: 1.21.3-1.16.3
Mod Loader: NeoForge 21.3.5
Java (available): 
- Zulu 8 - 8.0.4220.5
- Zulu 11 - 11.0.24.0
- Zulu 17 - 17.0.12.0
- Zulu 21 - 21.0.4.0
- Zulu 22 - 22.0.2.0
- Zulu 23 - 23.0.0.0

Java used: 
![Snímek obrazovky 2024-10-29 193150](https://github.com/user-attachments/assets/ec91ee15-dc66-47ef-8832-438873a84636)

compatibility level set to:
![Snímek obrazovky 2024-10-29 193412](https://github.com/user-attachments/assets/025337fb-a729-493c-95ea-d1881d47e051)

Specific errors:

> [29/10/2024 18:32:11 odp.] Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config smartbrainlib.mixins.json

> [29/10/2024 18:32:11 odp.] Caused by: java.lang.IllegalArgumentException: The specified resource 'smartbrainlib.mixins.json' was invalid or could not be read

Mod list (excel): [MC-Modpack-1-21-3--1.xlsx](https://github.com/user-attachments/files/17561329/MC-Modpack-1-21-3--1.xlsx)

Mod list (ZIP): [Minecraft-1.21.3-NeoForge-1.zip](https://github.com/user-attachments/files/17561405/Minecraft-1.21.3-NeoForge-1.zip)

logs and debug: [logs-debug.zip](https://github.com/user-attachments/files/17561449/logs-debug.zip)

**Comment by Tslat** [comment]
Why don't your attached logs have that error message in them?

**Comment by Tslat** [comment]
Fixed in 1.16.4

**Comment by Tron-Creeper2** [comment]
> Why don't your attached logs have that error message in them?

Simply: That I don't know, so I can't answer.
Thx for the fix
