### ISSUE TITLE
Can i somehow Reuse The SBL_LOADER for my own MemoryModuleTypes?

### ISSUE THREAD

**Issue by desertratx** [Tslat/SmartBrainLib#78]
Hey, 

I'm a bit new to Minecraft Modding and got a probably stupid question.

I tried to implement a new Sensor with a new MemoryModuleType. I tried to use the SBL_LOADER but got following error:
![image](https://github.com/user-attachments/assets/62064199-0967-47fe-8107-2b19583e422b)

Caused by: java.lang.IllegalStateException: Cannot register new entries to DeferredRegister after RegisterEvent has been fired.

Do I need to implement SBL_CONSTANTS + SBL_LOADER on my own, or can i somehow reuse it?

Greetings,
The Rat

**Comment by Tslat** [comment]
No

You should never be registering objects under another mod's ID or registries.

If you want to register your own MemoryModuleTypes, do so in your own mod with your own registry setup, same as you would for items, blocks, etc..

**Comment by desertratx** [comment]
Thought so, thx for the quick response! And thx for the great lib
